### PR TITLE
Map improvements 2

### PR DESCRIPTION
**Pull request by shermp**
Second round of map improvements, as discussed in #2 

I've removed the use of template literals and replaced it with a table function. Code is now IE11 compatible.

Zoom levels have been tweaked. You can now zoom in closer, and zooming in "too far" no longer results in a grey background

Timestamps are now parsed using Moment.js. Output is formatted for friendly viewing. There are a [lot](https://momentjs.com/docs/#/displaying/) of ways to display time. The best thing is, you can format the same timestamp in different ways depending on the situation

All libraries are now pulled into the repository instead of relying on CDN's

I've made the default marker a bit smaller. We might want to investigate using a custom marker in the future.

### CODE REVIEW

**Comment by SteveCossy** [comment]
We have broken something!  No base map or pins. :-( 
I copied the styles and scripts folders to my server.
I've checked permissions - everyone has read access to everything and x access to directories.
Tried:
* changing references in index.html to absolute
* changing references to leaflet.js and jquery-3.4.1.min.js back to remote sources
That didn't help.
Suggestions?
Given this whole project is beta, I've left the broken code there for now http://students.pcsupport.ac.nz/OSM/
The one that does work is here: http://students.pcsupport.ac.nz/OSM/index.19nov28
Attached is a copy of the commands I've used to test the changes.  
:-)

[MobaXterm_staff.pcsupport.ac.nzcosste_20191128_130505.txt](https://github.com/SteveCossy/IOT/files/3899220/MobaXterm_staff.pcsupport.ac.nzcosste_20191128_130505.txt)

**Comment by shermp** [comment]
Um, http://students.pcsupport.ac.nz/OSM/ works for me?

You may have to hard refresh the web page to force your browser to reload styles etc. `ctrl-F5`

**Comment by SteveCossy** [comment]
Works for me now too! :-D  Thank you very much!  (IE at work too.)
One other minor bug.  
When I tap a pin on my phone, both the tooltip and popup appear. No real problem, as the popup comes out on top, but if it is fixable, that would be nice.  I stumbled on this page yesterday that might help: https://stackoverflow.com/questions/55267558/show-leaflet-tooltip-on-hover-only-when-popup-is-not-being-shown
I will merge this change in the meantime.

I've also been thinking about the idea of having a list of alternative csv datasets to display.  Will start a new issue to discuss that.

**Comment by shermp** [comment]
Yeah, I should be able to sort the tooltip/popup clash. Thanks for the link.

Will get onto it later on this evening when I get home.

**Comment by shermp** [comment]
Interestingly, the map is now broken for me :( Don't know what's changed. Just getting an aqua background, no markers or anything.

**Comment by SteveCossy** [comment]
Likewise.  http://students.pcsupport.ac.nz/OSM/index.19nov28 still works (another rouge pin has turned up "Andrew!").  I'm going to swap the two around until we can sort what is stopping the new one for working consistently.  :-(  Would you like me to get you an account on students.pcsupport.ac.nz to use for debugging - or we could do a Zoom session, and I could let you use my screen to access the page.
Will the CLI scrollback that I sent earlier help at all?

**Comment by shermp** [comment]
I'm wondering if it can't read the geojson?

The initial map extents is derived from the features in the geojson. If it can't load the geojson, there are no markers, and who knows what the map extents will be...

**Comment by SteveCossy** [comment]
Lines that reference json are identical and the same file still works with the old js.
<pre>cosste@students:/var/www/html/OSM$ diff index.html index.19nov28 | grep -C 4 json</pre>
produced no output, so no 'json' lines have changed.  
Could it be in this loop?
<pre>    $.getJSON("RSSILatLong.geojson", function (data) {

      var geojson = L.geoJson(data, {
        onEachFeature: function (feature, layer) {
          var popup_html = `<table class="popup_table">
            <tr>
              <th>Time:</th><td>${feature.properties.TimeStamp}</td>
            </tr>
            <tr>
              <th>RSSI:</th><td>${feature.properties.RSSI}</td>
            </tr>
              <th>Lat:</th><td>${feature.properties.Lat}</td>
            <tr>
              <th>Long:</th><td>${feature.properties.Long}</td>
            </tr>
          </table>`;
          layer.bindPopup(popup_html);
          layer.bindTooltip(popup_html);
        }
      });


    $.getJSON("RSSILatLong.geojson", function (data) {
      var geojson = L.geoJson(data, {
        onEachFeature: function (feature, layer) {
          let ts = moment(feature.properties.TimeStamp);
          let ttTable = document.createElement('table');
          ttTable.classList.add('geopopup');
          addTableRow(ttTable, ['Time:', ts.format("DD/MM/YYYY h:mm:ssa")], false, true);
          addTableRow(ttTable, ['RSSI:', feature.properties.RSSI], false, true);
          // Note, we need two separate tables, hence the clone
          let popTable = ttTable.cloneNode(true);
          addTableRow(popTable, ['Lat:', feature.properties.Lat], false, true);
          addTableRow(popTable, ['Long:', feature.properties.Long], false, true);
          layer.bindPopup(popTable);
          layer.bindTooltip(ttTable);
        }
      });</pre>
BTW, I'll be out from about 3:30.

**Comment by SteveCossy** [comment]
BTW<sup>2</sup> http://students.pcsupport.ac.nz/OSM/index.19nov28 is going again now.  :-S

**Comment by shermp** [comment]
Ok, it's definitely something about that GeoJSON the map doesn't like.

I suspect it may have to do with the map extents. I'll do some more experimentation when I get home.

**Comment by SteveCossy** [comment]
That makes sense - the map failures might have coincided with the spurious
points I identified in an email this afternoon. There was another point
after the email ... and now it has happened again.
http://students.pcsupport.ac.nz/OSM/index.19nov28
You can download the geoJson from my site.

Better concentrate on the presentation here now..
😊

**Comment by shermp** [comment]
It was a combination of points existing in places outside the immediate area, and a minimum zoom level set.

Meant getting the extent was outside the allowed zoom level, which meant it centred the map somewhere in the middle (over cook strait).

Simple fix is to remove the minZoom requirement. I'll push the fix to master without opening a new PR.

**Pull request merged**
